# Generated by Django 5.2.1 on 2025-05-23 18:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('plain_text', 2), ('image', 3), ('gallery', 8), ('carousel', 8), ('button', 12), ('video', 14), ('iframe', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Párrafo enriquecido'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Texto simple'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto opcional', 'max_length': 250, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Imágenes'}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], 'help_text': 'Estilo del botón (Bootstrap)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('url', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'URL del video (YouTube o Vimeo)'}), 14: ('wagtail.blocks.StructBlock', [[('video_url', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'URL del contenido embebido'}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Altura (px)'}), 17: ('wagtail.blocks.StructBlock', [[('iframe_url', 15), ('height', 16)]], {})})),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Evento')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('plain_text', 2), ('image', 3), ('gallery', 8), ('carousel', 8), ('button', 12), ('video', 14), ('iframe', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Párrafo enriquecido'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Texto simple'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto opcional', 'max_length': 250, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Imágenes'}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], 'help_text': 'Estilo del botón (Bootstrap)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('url', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'URL del video (YouTube o Vimeo)'}), 14: ('wagtail.blocks.StructBlock', [[('video_url', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'URL del contenido embebido'}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Altura (px)'}), 17: ('wagtail.blocks.StructBlock', [[('iframe_url', 15), ('height', 16)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('plain_text', 2), ('image', 3), ('gallery', 8), ('carousel', 8), ('button', 12), ('video', 14), ('iframe', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Párrafo enriquecido'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Texto simple'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto opcional', 'max_length': 250, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Imágenes'}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], 'help_text': 'Estilo del botón (Bootstrap)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('url', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'URL del video (YouTube o Vimeo)'}), 14: ('wagtail.blocks.StructBlock', [[('video_url', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'URL del contenido embebido'}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Altura (px)'}), 17: ('wagtail.blocks.StructBlock', [[('iframe_url', 15), ('height', 16)]], {})})),
            ],
            options={
                'verbose_name': 'Inicio',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('plain_text', 2), ('image', 3), ('gallery', 8), ('carousel', 8), ('button', 12), ('video', 14), ('iframe', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Párrafo enriquecido'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Texto simple'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto opcional', 'max_length': 250, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Imágenes'}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], 'help_text': 'Estilo del botón (Bootstrap)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('url', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'URL del video (YouTube o Vimeo)'}), 14: ('wagtail.blocks.StructBlock', [[('video_url', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'URL del contenido embebido'}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Altura (px)'}), 17: ('wagtail.blocks.StructBlock', [[('iframe_url', 15), ('height', 16)]], {})})),
                ('fecha', models.DateField(verbose_name='Fecha de Publicación')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiasIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('plain_text', 2), ('image', 3), ('gallery', 8), ('carousel', 8), ('button', 12), ('video', 14), ('iframe', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Párrafo enriquecido'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Texto simple'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto opcional', 'max_length': 250, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Imágenes'}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], 'help_text': 'Estilo del botón (Bootstrap)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('url', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'URL del video (YouTube o Vimeo)'}), 14: ('wagtail.blocks.StructBlock', [[('video_url', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'URL del contenido embebido'}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Altura (px)'}), 17: ('wagtail.blocks.StructBlock', [[('iframe_url', 15), ('height', 16)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PaginaInformativaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('plain_text', 2), ('image', 3), ('gallery', 8), ('carousel', 8), ('button', 12), ('video', 14), ('iframe', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'label': 'Encabezado'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Párrafo enriquecido'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Texto simple'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagen', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Texto opcional', 'max_length': 250, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Imágenes'}), 8: ('wagtail.blocks.StructBlock', [[('images', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto del botón', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace del botón', 'required': True}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], 'help_text': 'Estilo del botón (Bootstrap)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('url', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'URL del video (YouTube o Vimeo)'}), 14: ('wagtail.blocks.StructBlock', [[('video_url', 13)]], {}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'URL del contenido embebido'}), 16: ('wagtail.blocks.IntegerBlock', (), {'default': 400, 'label': 'Altura (px)'}), 17: ('wagtail.blocks.StructBlock', [[('iframe_url', 15), ('height', 16)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PreguntasFrecuentesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('faqs', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('pregunta', 0), ('respuesta', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestimoniosPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('testimonios', wagtail.fields.StreamField([('testimonio', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('nombre', 0), ('comentario', 1), ('imagen', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
