# Generated by Django 5.2.1 on 2025-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_testimoniospage_page_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiapage',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
    ]
