# Generated by Django 5.2.1 on 2025-05-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactopage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactopage',
            name='horario',
            field=models.TextField(blank=True, verbose_name='Horario'),
        ),
    ]
