# Generated by Django 5.2.1 on 2025-05-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_contactopage_body_alter_eventopage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navitem',
            name='page',
        ),
        migrations.AddField(
            model_name='navitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.navitem'),
        ),
        migrations.AddField(
            model_name='navitem',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
