# Generated by Django 5.2.1 on 2025-05-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_footerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompage',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
