# Generated by Django 5.2.1 on 2025-05-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_custompage_show_in_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='show_in_footer',
            field=models.BooleanField(default=False, verbose_name='Mostrar en el footer'),
        ),
    ]
