# Generated by Django 5.2.1 on 2025-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_custompage_show_in_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
