# Generated by Django 5.2.1 on 2025-05-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_footermenupage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterMenuPage',
        ),
    ]
