# Generated by Django 5.2.1 on 2025-06-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_navitem_locale_navitem_translation_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='navitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='navitem',
            name='translation_key',
        ),
    ]
