# Generated by Django 5.2.1 on 2025-06-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_alter_articlepage_body_alter_contactopage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopage',
            name='mapa_url',
            field=models.URLField(blank=True, help_text='Enlace a Google Maps u otro servicio de mapas', verbose_name='URL del Mapa'),
        ),
    ]
