# Generated by Django 5.2.1 on 2025-06-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_eventopage_mapa_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventopage',
            name='mapa_url',
            field=models.TextField(blank=True, help_text='Enlace a Google Maps u otro servicio de mapas', verbose_name='URL del Mapa'),
        ),
    ]
